spring.datasource.url=jdbc:postgresql://localhost:5432/accommodation_db
spring.datasource.username=postgres
spring.datasource.password=pwd

spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
#spring.flyway.repair=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE