# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/accommodation_db
spring.datasource.username=postgres
spring.datasource.password=pwd

spring.flyway.validate-on-migrate=false
spring.jpa.hibernate.ddl-auto=validate

logging.level.org.hibernate.SQL=DEBUG
logging.level.com.example.lab_1=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# JWT
jwt.secret=${JWT_KEY}
jwt.expirationMs=86400000
